name: "Publish release to Notion"
description: "Creates a new page in an existing database with release information"
inputs:
  token:
    description: "Notion API token"
    required: true
  database-id:
    description: "Notion database ID"
    required: true
  name-id:
    description: "ID of the name column"
    required: true
  version-id:
    description: "ID of the version column"
    required: true
  date-id:
    description: "ID of the date column"
    required: true
  mac-download-id:
    description: "ID of the macOS download URL column"
    required: false
  win-download-id:
    description: "ID of the Windows download URL column"
    required: false
  base-download-url:
    description: "Download URL"
    required: false
  mac-file-path:
    description: "Filename of the macOS package. {{version}} will be replaced with the app's version"
    required: false
  win-file-path:
    description: "Filename of the Windows package. {{version}} will be replaced with the app's version"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
